plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "2.3.1"
    id 'com.gradleup.shadow' version '9.3.0'
}

group = 'org.proto68'
version = '1.0'

repositories {
    mavenCentral()
    maven { name = "papermc-repo"; url = "https://repo.papermc.io/repository/maven-public/" }
    maven { name = "enginehub"; url = "https://maven.enginehub.org/repo/" }
    maven { url = 'https://repo.extendedclip.com/releases/' }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.1.2.build.5-alpha")
    compileOnly("com.sk89q.worldedit:worldedit-bukkit:7.4.0")
    compileOnly("com.sk89q.worldguard:worldguard-bukkit:7.0.16")
    compileOnly("me.clip:placeholderapi:2.12.2")
    compileOnly("net.raidstone:WorldGuardEvents:1.18.1")
    implementation("com.zaxxer:HikariCP:5.1.0")
    implementation("org.slf4j:slf4j-nop:2.0.13")
}

// Disable the plain jar task entirely so it can't accidentally get deployed
tasks.jar {
    enabled = false
}

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    archiveBaseName.set("Jails")
    archiveClassifier.set("")
    archiveVersion.set("")
    destinationDirectory.set(
            file("C:/Users/mnogo/OneDrive/Desktop/Test Server/plugins")
    )
    relocate 'com.zaxxer.hikari', 'org.proto68.jails.libs.hikari'
}

build {
    dependsOn shadowJar
}

def targetJavaVersion = 25

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(targetJavaVersion)
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}